language: generic

os: osx

matrix:
  include:
    - os: linux
      env: COMPILER_NAME=gcc CXX=g++-5 CC=gcc-5
      addons:
        apt:
          packages:
            - g++-5
          sources: &sources
            - llvm-toolchain-precise
            - ubuntu-toolchain-r-test
    - os: linux
      env: COMPILER_NAME=clang CXX=clang++-3.8 CC=clang-3.8
      addons:
        apt:
          packages:
            - clang-3.8
          sources: *sources

install:
  # install cmake 2.8.12 manually, see
  #     * https://github.com/travis-ci-tester/travis-test-cmake
  - wget http://www.cmake.org/files/v2.8/cmake-2.8.12.tar.gz
  - tar xf cmake-2.8.12.tar.gz
  - cd cmake-2.8.12
  - ./bootstrap --system-curl
  - make
  - sudo make install
  - cd ..
  # -- end
  
script:
  - mkdir processing/compute_informer_order/build
  - cd processing/compute_informer_order/build
  - cmake .. && make

