sudo: required
dist: trusty

language: cpp

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env: 
        - COMPILER=g++-4.9
        - COMPILER_NAME=g++
        - COMPILER_VERSION=4.9
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
        - COMPILER=g++-5
        - COMPILER_NAME=g++
        - COMPILER_VERSION=5
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - clang-3.7
      env: 
        - COMPILER=clang++-3.7
        - COMPILER_NAME=clang
        - COMPILER_VERSION=3.7
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.8
          packages:
            - clang-3.8
      env: 
        - COMPILER=clang++-3.8
        - COMPILER_NAME=clang
        - COMPILER_VERSION=3.8
      
install:
  # install cmake 2.8.12 manually, see
  #     * https://github.com/travis-ci-tester/travis-test-cmake
  - wget http://www.cmake.org/files/v2.8/cmake-2.8.12.tar.gz
  - tar xf cmake-2.8.12.tar.gz
  - cd cmake-2.8.12
  - ./bootstrap --system-curl
  - make
  - sudo make install
  - cd ..
  # -- end
  
  # Download conan
  - wget http://downloads.conan.io/latest_debian -O conan.deb
  - sudo dpkg -i conan.deb
  - rm conan.deb

  # Automatic detection of your arch, compiler, etc
  - cd processing/compute_informer_order
  - conan install -s compiler=$COMPILER_NAME -s compiler.version=$COMPILER_VERSION
  - cd ..
  - cd ..
  
script:
  - mkdir processing/compute_informer_order/build
  - cd processing/compute_informer_order/build
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER .. && cmake --build .

