version: 0.1.{build}

platform:
  - x64

install:
  # Needed for C++
  - cmd: pip install conan
  # Needed for Python
  - cmd: pip install -r webapp/requirements.txt

build_script:
  # Build C++
  - cmd: mkdir build-release
  - cmd: cd build-release
  - cmd: conan install ../processing/compute_informer_order --build=missing
  - cmd: cmake ../processing/compute_informer_order -DBUILD_TEST=TRUE  -G "Visual Studio 14 2015 Win64"
  - cmd: cmake --build . --config Release
  - cmd: cd ..

test_script:
  # Ŕun C++ tests
  - cmd: build-release\bin\test_neutron_basic.exe
  # Run Python tests
  - cmd: python -m unittest discover -s webapp

