# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-01 19:33
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_auto_20160522_1236'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=256)),
                ('recipient', models.EmailField(max_length=254)),
                ('staff_recipient', models.IntegerField(choices=[(0, 'Managers'), (1, 'Admins')])),
                ('message', models.TextField()),
                ('json', jsonfield.fields.JSONField()),
                ('template', models.CharField(blank=True, max_length=60, null=True)),
                ('sent', models.DateTimeField(blank=True, null=True)),
                ('fail_count', models.IntegerField(default=0)),
            ],
        ),
    ]
