# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-02 22:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='notified',
            field=models.BooleanField(default=False, editable=False, help_text='Whether a mail has been enqueued with the response to the user.'),
        ),
        migrations.AlterField(
            model_name='email',
            name='staff_recipient',
            field=models.IntegerField(choices=[(0, 'Managers'), (1, 'Admins')], help_text='Managers: manager1@mail.com, manager2@mail.com</br>Admins: admin1@mail.com, admin2@mail.com'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.TextField(blank=True, help_text='Answer. Will send email to user', null=True),
        ),
    ]
