# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-17 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neutron', '0001_squashed_0017_auto_20160707_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='informer',
            name='known_us_choice',
            field=models.IntegerField(blank=True, choices=[(0, 'Cálamo y Cran'), (1, 'University'), (2, 'Other')], help_text='How did he know about us?', null=True),
        ),
    ]
