# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-11 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neutron', '0001_squashed_0015_auto_20160911_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='word_general_ci',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True),
        ),
    ]
