# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-17 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neutron', '0002_informer_known_us_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='informer',
            name='education_choice',
            field=models.IntegerField(blank=True, choices=[(0, 'Ed. Básica'), (1, 'Ed. Secundaria'), (2, 'Ed. Universitaria')], help_text='Educational level', null=True),
        ),
    ]
