# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-22 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neutron', '0002_remove_meaning_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='informer',
            name='privacy',
            field=models.IntegerField(choices=[(0, 'Public'), (1, 'Friends'), (2, 'Private')], default=0, help_text='Define who can see this information: public (everyone), friends (only users registered), private (nobody, just in database dumps).'),
        ),
        migrations.AddField(
            model_name='meaning',
            name='is_locution',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meaning',
            name='type',
            field=models.IntegerField(choices=[(0, 'Definition'), (1, 'Reference (remisi\xf3n)')], default=0),
        ),
    ]
