# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-11 10:42
from __future__ import unicode_literals

from django.db import migrations


def nothing(*args, **kwargs):
    pass

def populate_word_general_ci(apps, schema_editor):
    Word = apps.get_model("neutron", "Word")
    for w in Word.objects.all():
        w.word_general_ci = w.word
        w.save()  # Populate 'word_bin' field


class Migration(migrations.Migration):

    dependencies = [
        ('neutron', '0002_word_word_general_ci'),
    ]

    operations = [
        migrations.RunPython(populate_word_general_ci, nothing),
    ]
