# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-17 17:13
from __future__ import unicode_literals

import difflib
from django.db import migrations


def migrate_informers(apps, schema_editor):
    Informer = apps.get_model("neutron", "Informer")

    for informer in Informer.objects.all():
        known_us = None
        education = None
        try:
            education_list = ['universidad', 'master', 'secundaria', 'primaria', 'basica']
            item = difflib.get_close_matches(informer.education, education_list)
            if item in education_list[0:2]:
                education = Informer.KNOWN_US.university
            elif item in education_list[2:3]:
                education = Informer.KNOWN_US.secundaria
            elif item in education_list[3:]:
                education = Informer.KNOWN_US.basica
        except Exception as e:
            print("Error: {}".format(e))

        try:
            known_list = ['university', 'universidad', 'calamo & cran', 'calamo']
            item = difflib.get_close_matches(informer.known_us, known_list)
            if item in known_list[0:2]:
                known_us = Informer.KNOWN_US.university
            elif item in known_list[2:]:
                known_us = Informer.KNOWN_US.calamo
        except Exception as e:
            print("Error: {}".format(e))

        informer.known_us_choice = known_us
        informer.education_choice = education
        informer.save()


def nothing(*args, **kwargs):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('neutron', '0003_informer_education_choice'),
    ]

    operations = [
        migrations.RunPython(migrate_informers, nothing),
    ]
