# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-22 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neutron', '0003_auto_20160322_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='meaning',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
