# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-11 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neutron', '0003_auto_20160911_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='word_general_ci',
            field=models.CharField(editable=False, max_length=64),
        ),
    ]
