# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-17 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neutron', '0004_auto_20160717_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informer',
            name='education',
        ),
        migrations.RemoveField(
            model_name='informer',
            name='known_us',
        ),
        migrations.AlterField(
            model_name='informer',
            name='known_us_choice',
            field=models.IntegerField(blank=True, choices=[(0, 'Cálamo & Cran'), (1, 'University'), (2, 'Other')], help_text='How did he know about us?', null=True),
        ),
    ]
