# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-11 10:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neutron', '0004_auto_20160911_1044'),
    ]

    operations = [
        migrations.RunSQL(
            sql='alter table neutron_word modify word_general_ci VARCHAR(64) character set utf8 collate utf8_general_ci;',
            reverse_sql=''
        ),

    ]
