# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-17 17:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neutron', '0005_auto_20160717_1748'),
    ]

    operations = [
        migrations.RenameField(
            model_name='informer',
            old_name='education_choice',
            new_name='education',
        ),
        migrations.RenameField(
            model_name='informer',
            old_name='known_us_choice',
            new_name='known_us',
        ),
    ]
