# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-01 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neutron', '0005_auto_20160911_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='informer',
            name='is_living_region',
            field=models.NullBooleanField(help_text='The informer is currently living in his birth region'),
        ),
        migrations.AddField(
            model_name='informer',
            name='is_native_speaker',
            field=models.NullBooleanField(help_text='The informer is native speaker'),
        ),
        migrations.AddField(
            model_name='informer',
            name='is_no_abroad',
            field=models.NullBooleanField(help_text="The informer hasn't lived abroad for more than 6 months in the last 2 years"),
        ),
    ]
