# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-30 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neutron', '0005_auto_20160322_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='informer',
            name='searchable',
            field=models.BooleanField(default=False, help_text='Whether the words related to this informer are included in the search-form.'),
        ),
    ]
