# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-22 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neutron', '0006_informer_searchable'),
    ]

    operations = [
        migrations.AddField(
            model_name='informer',
            name='education',
            field=models.CharField(default='', help_text='Educational level', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='informer',
            name='known_us',
            field=models.CharField(default='', help_text='How did he know about us', max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='informer',
            name='nacionality',
            field=models.CharField(default='', help_text='Nacionality set by the user', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='informer',
            name='surname',
            field=models.CharField(default='', help_text='Informer surname', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='informer',
            name='name',
            field=models.CharField(help_text='Informer name', max_length=64),
        ),
    ]
