# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neutron', '0006_auto_20160717_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='language_code',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
