# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-18 18:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neutron', '0007_region_language_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='region',
            old_name='language_code',
            new_name='_language_code',
        ),
    ]
