# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-03 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neutron', '0008_auto_20160718_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='informer',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='informer',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(0, 'Male'), (1, 'Female')], null=True),
        ),
    ]
