# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-22 17:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neutron', '0008_auto_20160522_1853'),
    ]

    operations = [
        migrations.RenameField(
            model_name='informer',
            old_name='nacionality',
            new_name='nationality',
        ),
    ]
