# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-22 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neutron', '0009_auto_20160522_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informer',
            name='education',
            field=models.CharField(blank=True, help_text='Educational level', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='informer',
            name='known_us',
            field=models.CharField(blank=True, help_text='How did he know about us', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='informer',
            name='nationality',
            field=models.CharField(blank=True, help_text='Nacionality set by the user', max_length=128, null=True),
        ),
    ]
