# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-12 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neutron', '0009_auto_20160803_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='informer',
            name='honor_code',
            field=models.BooleanField(default=False, help_text='Honor code, needed to access data'),
        ),
        migrations.AlterField(
            model_name='informer',
            name='name',
            field=models.CharField(help_text='Informer identifier (only in admin)', max_length=64),
        ),
    ]
