# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-23 18:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neutron', '0010_auto_20160522_1927'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='region',
            managers=[
            ],
        ),
    ]
