# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-23 19:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neutron', '0011_auto_20160523_2021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informer',
            name='nationality',
        ),
    ]
