# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-11 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neutron', '0012_auto_20160911_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='word_bin',
            field=models.CharField(db_index=True, max_length=64),
        ),
    ]
