# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-10 13:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neutron', '0012_remove_informer_nationality'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordAlternate',
            fields=[
                ('datum_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='neutron.Datum')),
            ],
            options={
                'verbose_name': 'Word alternate',
                'verbose_name_plural': 'Word alternates',
            },
            bases=('neutron.datum',),
        ),
        migrations.RemoveField(
            model_name='worduse',
            name='alternative',
        ),
        migrations.AddField(
            model_name='datum',
            name='elapsed_time',
            field=models.FloatField(blank=True, help_text='Number of seconds for the user to answer the given question.', null=True),
        ),
        migrations.AddField(
            model_name='meaning',
            name='excluded',
            field=models.BooleanField(default=False, help_text="If set, this meaning won't be shown to informers in WordUse and WordAlternate interfaces"),
        ),
        migrations.AddField(
            model_name='word',
            name='excluded',
            field=models.BooleanField(default=False, help_text="If set, this word won't be shown to informers in WordCoarse interface"),
        ),
        migrations.AlterField(
            model_name='worduse',
            name='meaning',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='neutron.Meaning'),
        ),
        migrations.AlterField(
            model_name='worduse',
            name='use',
            field=models.IntegerField(choices=[(0, 'Ok'), (1, "I don't use it, but I have heard it"), (1, 'Neither use it, nor heard it before'), (2, 'Do not recognize this meaning for this word')]),
        ),
        migrations.AddField(
            model_name='wordalternate',
            name='alternative',
            field=models.ForeignKey(blank=True, help_text="Alternate word/definition in the informer's dictionary", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alternate_set', to='neutron.Meaning'),
        ),
        migrations.AddField(
            model_name='wordalternate',
            name='meaning',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='neutron.Meaning'),
        ),
    ]
