# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-11 09:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neutron', '0013_auto_20160911_0828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='word_bin',
        ),
    ]
