# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-11 09:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neutron', '0014_remove_word_word_bin'),
    ]

    operations = [
        migrations.RunSQL("alter table neutron_word modify word VARCHAR(64) character set utf8 collate utf8_bin;"),
    ]
