# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-13 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neutron', '0014_auto_20160610_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worduse',
            name='value',
            field=models.IntegerField(choices=[(0, 'Ok'), (1, "I don't use it, but I have heard it"), (2, 'Neither use it, nor heard it before'), (3, 'Do not recognize this meaning for this word')]),
        ),
    ]
