# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-02 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neutron', '0015_auto_20160613_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coarseword',
            name='value',
            field=models.BooleanField(help_text='Checked if the word has been marked as coarse.'),
        ),
    ]
