# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-07 18:18
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('neutron', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlternateData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.FloatField(help_text='Percentage of use of this word as the alternate for the given one', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neutron.Word')),
            ],
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Identifier for this synthetic data configuration', max_length=255)),
                ('comments', models.TextField(blank=True, null=True)),
                ('seed', models.IntegerField(blank=True)),
                ('n_informers', models.IntegerField()),
                ('generated', models.BooleanField(default=False, help_text='Whether the informers have been already generated')),
            ],
            options={
                'verbose_name': 'Configuration',
                'verbose_name_plural': 'Configurations',
            },
        ),
        migrations.CreateModel(
            name='InformerGenerated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seed', models.IntegerField(blank=True)),
                ('randomness', models.FloatField(default=0.0, help_text='How much this informer data is away from gold-standard', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('n_use_data', models.IntegerField(editable=False, help_text='Number of data related to word use')),
                ('n_coarse_data', models.IntegerField(editable=False, help_text='Number of coarse data informed')),
                ('generated', models.BooleanField(default=False, help_text='Whether the data have been already generated')),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='synthetic.Configuration')),
                ('informer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neutron.Informer')),
            ],
        ),
        migrations.CreateModel(
            name='RegionData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.FloatField(blank=True, help_text='Percentage of informers for this region', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('min_use_data', models.IntegerField(default=0, help_text='Minimum amount of data provided by each informer about word use')),
                ('max_use_data', models.IntegerField(help_text='Maximum amount of data provided by each informer about word use')),
                ('min_coarse_data', models.IntegerField(default=0, help_text='Minimum amount of data provided by each informer about coarsity')),
                ('max_coarse_data', models.IntegerField(help_text='Maximum amount of data provided by each informer about coarsity')),
                ('beta_a', models.FloatField(default=2, help_text='Parameter "a" for beta distribuition', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('beta_b', models.FloatField(default=100, help_text='Parameter "b" for beta distribution', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('random', models.BooleanField(default=False)),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='synthetic.Configuration')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neutron.Region')),
            ],
            options={
                'verbose_name': 'Region data',
                'verbose_name_plural': 'Regions data',
            },
        ),
        migrations.CreateModel(
            name='WordCoarseData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coarse', models.FloatField(help_text='Percentage of people that mark this word as coarse', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='synthetic.Configuration')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neutron.Region')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neutron.Word')),
            ],
        ),
        migrations.CreateModel(
            name='WordMeaningData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ok', models.FloatField(help_text='Percentage of people that recognize the word with the meaning', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('unknown', models.FloatField(help_text='Percentage of people that do not recognize the word with the meaning', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='synthetic.Configuration')),
                ('meaning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neutron.Meaning')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neutron.Region')),
            ],
        ),
        migrations.AddField(
            model_name='alternatedata',
            name='wordmeaningdata',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='synthetic.WordMeaningData'),
        ),
        migrations.AlterUniqueTogether(
            name='wordmeaningdata',
            unique_together=set([('configuration', 'region', 'meaning')]),
        ),
        migrations.AlterUniqueTogether(
            name='wordcoarsedata',
            unique_together=set([('configuration', 'region', 'word')]),
        ),
        migrations.AlterUniqueTogether(
            name='regiondata',
            unique_together=set([('configuration', 'region')]),
        ),
    ]
