# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 17:25
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('neutron', '0002_auto_20160223_2222'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlternateData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.FloatField(help_text='Percentage of use of this word as the alternate for the given one', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
            ],
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Identifier for this synthetic data configuration', max_length=255)),
                ('seed', models.IntegerField(editable=False)),
                ('n_informers', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Configuration',
                'verbose_name_plural': 'Configurations',
            },
        ),
        migrations.CreateModel(
            name='InformerGenerated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seed', models.IntegerField(editable=False)),
                ('n_use_data', models.IntegerField(editable=False, help_text='Number of data related to word use')),
                ('n_coarse_data', models.IntegerField(editable=False, help_text='Number of coarse data informed')),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='synthetic.Configuration')),
                ('informer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neutron.Informer')),
            ],
        ),
        migrations.CreateModel(
            name='RegionData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_use_data', models.IntegerField(default=0, help_text='Minimum amount of data provided by each informer about word use')),
                ('max_use_data', models.IntegerField(help_text='Maximum amount of data provided by each informer about word use')),
                ('min_coarse_data', models.IntegerField(default=0, help_text='Minimum amount of data provided by each informer about coarsity')),
                ('max_coarse_data', models.IntegerField(help_text='Maximum amount of data provided by each informer about coarsity')),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='synthetic.Configuration')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neutron.Region')),
            ],
        ),
        migrations.CreateModel(
            name='WordDefinitionData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coarse', models.FloatField(help_text='Percentage of people that mark this word as coarse', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('ok', models.FloatField(help_text='Percentage of people that recognize the word with the definition', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('unknown', models.FloatField(help_text='Percentage of people that do not recognize the word with the definition', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='synthetic.Configuration')),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neutron.Definition')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neutron.Region')),
            ],
        ),
        migrations.AddField(
            model_name='alternatedata',
            name='definition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='synthetic.WordDefinitionData'),
        ),
        migrations.AddField(
            model_name='alternatedata',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neutron.Word'),
        ),
        migrations.AlterUniqueTogether(
            name='worddefinitiondata',
            unique_together=set([('configuration', 'region', 'definition')]),
        ),
        migrations.AlterUniqueTogether(
            name='regiondata',
            unique_together=set([('configuration', 'region')]),
        ),
    ]
