# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synthetic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='seed',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='informergenerated',
            name='seed',
            field=models.IntegerField(),
        ),
    ]
