# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synthetic', '0002_auto_20160227_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='regiondata',
            name='mean',
            field=models.FloatField(default=0, help_text='Mean for lognorm distribuition'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='regiondata',
            name='std_dev',
            field=models.FloatField(default=0, help_text='Standard deviation for lognorm distribution'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='configuration',
            name='seed',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='informergenerated',
            name='seed',
            field=models.IntegerField(blank=True),
        ),
    ]
