# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 17:51
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synthetic', '0003_auto_20160227_1740'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='regiondata',
            options={'verbose_name': 'Region data', 'verbose_name_plural': 'Regions data'},
        ),
        migrations.AddField(
            model_name='regiondata',
            name='percentage',
            field=models.FloatField(blank=True, default=0, help_text='Percentage of informers for this region', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
            preserve_default=False,
        ),
    ]
