# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synthetic', '0004_auto_20160227_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regiondata',
            name='mean',
            field=models.FloatField(default=0, help_text='Mean for lognorm distribuition'),
        ),
        migrations.AlterField(
            model_name='regiondata',
            name='std_dev',
            field=models.FloatField(default=0.25, help_text='Standard deviation for lognorm distribution'),
        ),
    ]
