# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 20:39
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synthetic', '0005_auto_20160227_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='generated',
            field=models.BooleanField(default=False, help_text='Whether the informers have been already generated'),
        ),
        migrations.AddField(
            model_name='informergenerated',
            name='randomness',
            field=models.FloatField(default=0, help_text='How much this informer data is away from gold-standard', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
            preserve_default=False,
        ),
    ]
