# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synthetic', '0006_auto_20160227_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='informergenerated',
            name='generated',
            field=models.BooleanField(default=False, help_text='Whether the data have been already generated'),
        ),
    ]
