# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-04 17:04
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neutron', '0002_auto_20160223_2222'),
        ('synthetic', '0008_configuration_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordCoarseData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coarse', models.FloatField(help_text='Percentage of people that mark this word as coarse', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='synthetic.Configuration')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neutron.Region')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neutron.Word')),
            ],
        ),
        migrations.RemoveField(
            model_name='worddefinitiondata',
            name='coarse',
        ),
        migrations.AlterUniqueTogether(
            name='wordcoarsedata',
            unique_together=set([('configuration', 'region', 'word')]),
        ),
    ]
