# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-04 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synthetic', '0009_auto_20160304_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regiondata',
            name='mean',
        ),
        migrations.RemoveField(
            model_name='regiondata',
            name='std_dev',
        ),
        migrations.AddField(
            model_name='regiondata',
            name='beta_a',
            field=models.FloatField(default=0, help_text='Parameter "a" for beta distribuition'),
        ),
        migrations.AddField(
            model_name='regiondata',
            name='beta_b',
            field=models.FloatField(default=0.25, help_text='Parameter "b" for beta distribution'),
        ),
    ]
