# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-06 11:51
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synthetic', '0011_auto_20160304_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='regiondata',
            name='random',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='informergenerated',
            name='randomness',
            field=models.FloatField(default=0.0, help_text='How much this informer data is away from gold-standard', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='regiondata',
            name='beta_a',
            field=models.FloatField(default=2, help_text='Parameter "a" for beta distribuition', validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='regiondata',
            name='beta_b',
            field=models.FloatField(default=100, help_text='Parameter "b" for beta distribution', validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
