# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-19 13:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket', models.CharField(max_length=64)),
                ('key', models.CharField(max_length=255)),
                ('name', models.CharField(help_text='This will be the folder inside Amazon S3 bucket', max_length=64, unique=True)),
                ('user', models.ForeignKey(blank=True, help_text='Who ordered this export (blank for system)', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExportIndexManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='IncrementalFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket', models.CharField(max_length=64)),
                ('key', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField()),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exporter.ExportIndex')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OverrideFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket', models.CharField(max_length=64)),
                ('key', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField()),
                ('index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exporter.ExportIndex')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
