# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-19 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exporter', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExportIndexManager',
        ),
        migrations.AlterField(
            model_name='incrementalfile',
            name='end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incrementalfile',
            name='start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
