# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-19 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exporter', '0002_auto_20160319_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incrementalfile',
            name='end',
            field=models.DateField(),
        ),
    ]
