# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-19 14:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('exporter', '0003_auto_20160319_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='incrementalfile',
            name='name',
            field=models.CharField(default=datetime.datetime(2016, 3, 19, 14, 42, 46, 223596, tzinfo=utc), max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='overridefile',
            name='end',
            field=models.DateField(default=datetime.datetime(2016, 3, 19, 14, 42, 52, 135802, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='overridefile',
            name='name',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
