# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-19 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exporter', '0004_auto_20160319_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportindex',
            name='last_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
