# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-19 16:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exporter', '0005_exportindex_last_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='incrementalfile',
            unique_together=set([('version', 'name', 'start', 'end')]),
        ),
        migrations.AlterUniqueTogether(
            name='overridefile',
            unique_together=set([('version', 'name', 'end')]),
        ),
    ]
