# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-19 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exporter', '0006_auto_20160319_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportindex',
            name='last_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incrementalfile',
            name='end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='incrementalfile',
            name='start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='overridefile',
            name='end',
            field=models.DateTimeField(),
        ),
    ]
