# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-19 20:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exporter', '0007_auto_20160319_1743'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='incrementalfile',
            unique_together=set([('version', 'name', 'index', 'start', 'end')]),
        ),
        migrations.AlterUniqueTogether(
            name='overridefile',
            unique_together=set([('version', 'name', 'index')]),
        ),
    ]
